name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Welcome to the Hydro-Kinetics repository, you are helping to improve this team!"
        pr-message: "Welcome to the Hydro-Kinetics repository, thanks for trying to improve this team!"
